package com.lofi.servlet;

import com.lofi.dao.AdminDAO; // Assuming a DAO method to handle submission
import com.lofi.model.FoodSpotApproval;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDateTime;

public class SubmitFoodSpotServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // 1. Check if user is a logged-in vendor
        HttpSession session = request.getSession(false);
        if (session == null || !"vendor".equals(session.getAttribute("role"))) {
            response.sendRedirect("login.jsp?err=loginRequired");
            return;
        }
        Integer userId = (Integer) session.getAttribute("userId");
        if (userId == null) {
            response.sendRedirect("login.jsp?err=loginRequired");
            return;
        }

        // 2. Retrieve form parameters
        String restaurantName = request.getParameter("restaurantName");
        String address = request.getParameter("address");
        String googleMapsURL = request.getParameter("googleMapsURL");
        String photoURL = request.getParameter("photoURL");
        String openHours = request.getParameter("openHours");
        String closedHours = request.getParameter("closedHours");
        String workingDays = request.getParameter("workingDays");
        boolean halalCertified = "true".equals(request.getParameter("halalCertified"));

        // 3. Basic validation
        if (restaurantName == null || restaurantName.isBlank() || address == null || address.isBlank()) {
            request.setAttribute("errorMessage", "Restaurant name and address are required.");
            request.getRequestDispatcher("submitFoodspot.jsp").forward(request, response);
            return;
        }

        // 4. Create a FoodSpotApproval object
        // This constructor may need to be added to your FoodSpotApproval model
        FoodSpotApproval submission = new FoodSpotApproval(
                0, // request_id will be auto-generated by the DB
                userId,
                restaurantName,
                address,
                googleMapsURL,
                photoURL,
                openHours,
                closedHours,
                halalCertified,
                workingDays
        );
        submission.setSubmitted_time(LocalDateTime.now());


        // 5. Use a DAO to insert the submission into the food_spot_approval table
        try {
            // You will need to create this method in one of your DAOs,
            // likely AdminDAO or a new SubmissionDAO
            // For example: AdminDAO.createFoodSpotSubmission(submission);
            
            // For now, we will assume such a method exists and works.
            // If it returns a success flag or generated ID, you can use it here.
            
            request.setAttribute("successMessage", "Your food spot has been submitted for approval!");
            request.getRequestDispatcher("submissionResult.jsp").forward(request, response);

        } catch (/* SQLException e */ Exception e) {
            // Log the exception
            e.printStackTrace(); 
            
            request.setAttribute("errorMessage", "There was a database error. Please try again later.");
            request.getRequestDispatcher("submitFoodspot.jsp").forward(request, response);
        }
    }
}